version: '3.7'

services:
  composer:
    image: composer:1.6
    working_dir: /code
    volumes:
      - .:/code
    command: composer install -n --ignore-platform-reqs --no-scripts
    
networks:
  default:
    name: ${DOCKER_DEFAULT_NETWORK}